#!/bin/bash
cat $1 | awk --source '
  BEGIN	   {  
	 q="\""
	 First = 1      
	 In = 1
  }
  /^"""</,/^>"""/ {  next } 
  /^"""/	  {  Once = 1
                     In = 1 - In       
		     if (In) 
		       print "```"
		     else	  
		       if (First)   
			 First = 0   
		       else     
			 print "```"  
		     next }       
  ! First { print $$0 }       
  END     { if (In ) print "```"
            if (!Once) print "```"  }
' 